{% set name = "minestrone" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/minestrone-{{ version }}.tar.gz
  sha256: 773cda392f1015c8a9f5f06932b92cec0575a39624ec96cb6b41d199d0d726b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0
    - selectolax

test:
  imports:
    - minestrone
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamghill/minestrone/
  doc_url: https://minestrone.readthedocs.io/en/latest/
  summary: Search, modify, and parse messy HTML with ease.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
