{% set name = "minestrone" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/minestrone-{{ version }}.tar.gz
  sha256: 7c6fb40301d4b69d27470693cfaa14ad2cae3921820a81451b293f6d11a69d47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - beautifulsoup4 >=4.10.0,<5.0.0

test:
  imports:
    - minestrone
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamghill/minestrone/
  doc_url: https://minestrone.readthedocs.io/en/latest/
  summary: Search, modify, and parse messy HTML with ease.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
